config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users

  resources :events
  resources :users
  resources :attendances
  post "events/:id/attendances", to: "attendances#new", as: "inscription"
  resources :charges, only:[:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  after_create :participation_confirmation

  def participation_confirmation
    AttendanceMailer.participate_mail(self.event.administrator,self.user, self.event).deliver_now
  end



end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :users, through: :attendance
  belongs_to :administrator, class_name: "User"

  validates :start_date, presence: {message:"La date de départ doit être renseignée"}
  validate :is_gone?

  validates :duration, presence: {message:"La durée de l'évênement doit être renseignée"},
                      numericality: {greater_than: 0}
  validate :multiple_of_5?

  validates :title, presence: {message: "Le titre de l'évênement doit être présent"},
                    length: {minimum: 5, maximum: 140, message: "Le titre doit être compris entre 5 et 140 caractères"}

  validates :description, presence: {message: "La description doit être renseignée"},
                          length: {minimum: 20,maximum: 1000, message: "Le titre doit être compris entre 20 et 1000 caractères"}

  validates :price, presence: {message: "le prix doit être renseignée"},
                    numericality: { only_integer: true, greater_than: 1, less_than: 1000, message:" Le prix doit être un chiffre entier compris entre 1 et 1000" }

  validates :location, presence: {message: "Le lieu de l'évênement doit être renseigné"}

  def multiple_of_5?
    #c'est une erreur tant que c'est pas la vérité
    if self.duration != nil
    errors.add(:duration, "La duree doit etre un multiple de 5 !") unless
    self.duration % 5 == 0
    end
  end

  def is_gone?
    if self.start_date != nil
    erros.add(:start_date, " Tu ne peux pas modifier ou créer une évênement dans le passé.") unless
    self.start_date >  Time.now
    end
  end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end


  has_many :attendances, dependent: :destroy
  has_many :events, through: :attendance, dependent: :destroy
  has_many :administrator_events, foreign_key: "administrator_id", class_name: "Event", dependent: :destroy

  validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "L'email doit être renseigné au bon format (email@eamil.email) !"},
            uniqueness: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

    def configure_devise_parameters
      devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
      devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
    end

    include EventsHelper
    include AttendancesHelper
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
  end

  def show
  end

  def new
    @event = Event.find(params[:id])
    create
  end

  def create
    # Amount in cents
    @event = Event.find(params[:id])
    @attendances = Attendance.all

    @amount = @event.price
    @user=current_user

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

   charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Paiement de #{@user.first_name} #{@user.last_name}',
      currency: 'eur',
    })

    if charge
    @attendance = Attendance.new(user_id: current_user.id, event_id: @event.id, stripe_customer_id: customer.id)
    @attendance.save
    flash[:success] = "Vous êtes bien inscrit à #{@event.title}"
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
end

def create
  # Amount in cents
  @amount = 500
  @user=current_user

  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: 'Paiement de #{@user.first_name} #{@user.last_name}',
    currency: 'eur',
  })

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, only: [:show,:new,:create,:edit,:update,:destroy]

  def index
    @events = Event.all
    @attendances = Attendance.all
  end

  def show
    @event = Event.find(params[:id])
    @user = User.all
    @attendances = Attendance.all
  end

  def new
    @event = current_user
    @event = Event.new
  end

  def create
    @event = Event.new(administrator_id: current_user.id, start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location] ) # avec xxx qui sont les données obtenues à partir du formulaire

    if @event.save
      flash[:success] = "L'Event a bien été crée"
      redirect_to event_path(@event)
        else
      flash.now[:danger] = "Erreur, l'Event non créé"
      render "events/new"
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
      if @event.update(administrator_id: current_user.id, start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location])
        flash[:success] = "L'event a bien été modifié"
        redirect_to event_path(@event)
      else
        flash.now[:danger] = "L'event n'a pas été modifié"
        render :edit
      end
    end


  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = "L'Event a bien été supprimé"
    redirect_to root_path

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @users = current_user
    @events = Event.all
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def attendances_include?(event,attendances)
    attendances.find_by(user: current_user.id, event: event.id) == nil
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def compare(user_id,session_id)
    return user_id == session_id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<h2>Thanks, you paid <strong><%= @event.price %> </strong>!</h2>

app/views/attendances/destroy.html.erb
<h1>Attendances#destroy</h1>
<p>Find me in app/views/attendances/destroy.html.erb</p>

app/views/attendances/edit.html.erb
<h1>Attendances#edit</h1>
<p>Find me in app/views/attendances/edit.html.erb</p>

app/views/attendances/index.html.erb
<h1>Attendances#index</h1>
<p>Find me in app/views/attendances/index.html.erb</p>

app/views/attendances/new.html.erb
<h2>Thanks, you paid <strong> <%= @event.price %> </strong> ! </h2>

app/views/attendances/show.html.erb
<h1>Attendances#show</h1>
<p>Find me in app/views/attendances/show.html.erb</p>

app/views/attendances/update.html.erb
<h1>Attendances#update</h1>
<p>Find me in app/views/attendances/update.html.erb</p>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: 5.00 €</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Paiement pour participer à l'évênement"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<style>
body
{background-image: url('http://4everstatic.com/images/abstrait/fond-de-couleur-220805.jpg');
   background-repeat: no-repeat;
   background-size:cover;
   background-attachment:fixed;}
</style>

<body>
<center>
    <!-- ... -->
<br/><br/>
<% if @event.errors.any? %>
      <p>Nous n'avons pas réussi à créer l'évênement pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li style="color:red;"><%= message %></li>
        <% end %>
      </ul>
<% end %>

<p> Modifie ton Evenement </p>
    <%= form_tag url_for(action: 'update'), method: "patch" do %>

      <%= label_tag "Titre de l'évênement" %>
      <%= text_field_tag 'title', @event.title %>
      <br /> <br />

      <%= label_tag 'Date' %>
      <%= text_field_tag 'start_date', @event.start_date %>
      <br /> <br />

      <%= label_tag 'Durée' %>
      <%= text_field_tag 'duration', @event.duration %>
      <br /> <br />

      <%= label_tag 'Lieu' %>
      <%= text_field_tag 'location', @event.location %>
      <br /> <br />

      <%= label_tag 'Prix' %>
      <%= text_field_tag 'price', @event.price %>
      <br /> <br />

      <%= label_tag 'description:' %>
      <%= text_area_tag 'description', @event.description %>
      <br /> <br />

      <%= submit_tag "Modifie ton Event" %>

    <% end %>

    <!-- ... -->
</center>
</body>

app/views/events/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Events Chris</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>

<style> .jumbotron {
  height: 600px;
  background-image: url("https://landerapp.com/blog/wp-content/uploads/2018/05/eventsPinboard.jpg");
  background-repeat: no-repeat;
  background-size:cover;
  background-attachment:fixed;
}
</style>
  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="#" class="text-white">Follow on Twitter</a></li>
                <li><a href="#" class="text-white">Like on Facebook</a></li>
                <li><a href="#" class="text-white">Email me</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
          <% if current_user %>
          <div class="container">
            <h1 class="jumbotron-heading">Event Chris</h1>
            <p class="lead text">Bonjour <%= current_user.first_name %> heureux de te revoir! <br> A quel prochain évênement tu vas participer?<br> Ou peut-être tu es de retour pour créer ton évênement?</p>
          </div>
          <% else %>
        <div class="container">
          <h1 class="jumbotron-heading">Event Chris</h1>
          <p class="lead text">Bienvenue sur le site de tous les Event, <br> inscrit toi, <br>
            participe à des évênements,<br>créer tes évênements <br> et VIE TA VIE DE ROCKSTAR</p>
        </div>
        <% end %>
      </section>

      <div class="card-columns container mx-auto">
        <% @events.each do |t| %>
          <center>
            <div class="card shadow" style="width: 20rem; padding-bottom:10px; border-color:#781D47;">
              <img class="card-img-top" src="https://assets-global.website-files.com/5b7918ae4c34866ca737694c/5d47be1acc4d3a3adfb873b7_event-info.jpg" alt="Card image cap">
              <div class="card-body">
                <a style="color: #781D47; " class="card-title" href="http://localhost:3000/events/<%=t.id%>"> <%=t.title %></a>
                <p class="card-text"> Description : <%= t.description  %></p>
                <p class="card-text"> Prix : <%= t.price  %> €</p>
                <p class="card-text"><small class="text-muted"> Date de l'évènement: <%= t.start_date %></small></p>
                <p class="card-text"><small class="text-muted"> Durée de l'évènement: <%= t.duration %> min </small></p>
                <p class="card-text"><small class="text-muted"> Date de fin de l'évènement: <%=t.start_date + t.duration*60 %> </small></p>
                <p class="card-text"><small class="text-muted"> Nombre de participant: <%=@attendances.where(event_id: t.id).count %> </small></p>
                <button type="button"> <%=link_to "Voir plus", event_path(t.id) %> </button>
                <% if user_signed_in? && compare(t.administrator_id, current_user.id) %>
                <button type="button" class="btn btn-sm btn-outline-secondary"><%=link_to "Edit", edit_event_path(t.id) %></button>
                <button type="button" class="btn btn-sm btn-danger text-color:black"><%=link_to "Supprimer", event_path(t.id), method: :delete, data: {confirm: "êtes vous sur de vouloir supprimer cette évênement?"} %></button>
                <% else %>
                <% end %>
              </div>
            </div>
            <br>
          </center>
        <%end %>
      </div>


    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
          </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
  </body>
</html>

app/views/events/new.html.erb
<style>
body
{background-image: url('http://4everstatic.com/images/abstrait/fond-de-couleur-220805.jpg');
   background-repeat: no-repeat;
   background-size:cover;
   background-attachment:fixed;}
</style>

<body>
<center>
    <!-- ... -->
<br/><br/>
<% if @event.errors.any? %>
      <p>Nous n'avons pas réussi à créer l'évênement pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li style="color:red;"><%= message %></li>
        <% end %>
      </ul>
<% end %>

<p> Creer ton Evenement </p>
    <%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag "Titre de l'évênement" %>
      <%= text_field_tag 'title', @event.title %>
      <br /> <br />

      <%= label_tag 'Date' %>
      <%= text_field_tag 'start_date', @event.start_date %>
      <br /> <br />

      <%= label_tag 'Durée' %>
      <%= text_field_tag 'duration', @event.duration %>
      <br /> <br />

      <%= label_tag 'Lieu' %>
      <%= text_field_tag 'location', @event.location %>
      <br /> <br />

      <%= label_tag 'Prix' %>
      <%= text_field_tag 'price', @event.price %>
      <br /> <br />

      <%= label_tag 'description:' %>
      <%= text_area_tag 'description', @event.description %>
      <br /> <br />

      <%= submit_tag "Creation de l'Event" %>

    <% end %>

    <!-- ... -->
</center>
</body>

app/views/events/show.html.erb
<style>
body
{background-image: url('http://4everstatic.com/images/abstrait/fond-de-couleur-220805.jpg');
   background-repeat: no-repeat;
   background-size:cover;
   background-attachment:fixed;}
</style>

<body>
  <br><br>
  <center>
  <% h = @event.administrator_id %>
    <div class="card text-center mx-auto" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= @event.title %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%=@event.created_at.strftime("%d/%m/%Y") %></h6>
        <h6 class="card-subtitle mb-2 text-muted">modifié le: <%=@event.updated_at.strftime("%d/%m/%Y")%></h6>
        <h6 class="card-subtitle mb-2 text-muted">Crée par: <%= @user.find(@event.administrator_id).first_name %> </h6>
        <p class="card-text"><%= @event.description %></p>
        <p class="card-text"> Lieu: <%= @event.location %></p>
        <p class="card-text"> Durée: <%= @event.duration %> min</p>
        <p class="card-text"> Date: <%= @event.start_date %> </p>
        <p class="card-text"> Date de fin de l'évènement: <%=@event.start_date + @event.duration*60 %> </p>
        <p class="card-text"><small class="text-muted"> Nombre de participant: <%=@attendances.where(event_id: @event.id).count %> </small></p>

        <% if attendances_include?(@event,@attendances) %>
        <%= form_tag inscription_path do %>
          <article>
            <% if flash[:error].present? %>
              <div id="error_explanation">
                <p><%= flash[:error] %></p>
              </div>
            <% end %>
            <label class="amount">
              <span>Prix: <%=@event.price %> €</span>
            </label>
          </article>

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="Paiement pour participer à l'évênement"
                  data-amount="<%= @event.price.to_f * 100 %>"
                  data-currency="eur"
                  data-locale="auto"></script>
        <% end %>
        <%end %>

        <% if compare(@event.administrator_id, current_user.id) %>
        <button type="button" class="btn btn-sm btn-outline-secondary"><%=link_to "Edit", edit_event_path(@event.id) %></button>
        <button type="button" class="btn btn-sm btn-danger text-color:black"><%=link_to "Supprimer", event_path(@event.id), method: :delete, data: {confirm: "êtes vous sur de vouloir supprimer cette évênement?"}%></button>

       <%end%>

       <br /><br />
  </center>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Event Chris</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <!-- NavBar --!>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand"<%= link_to "THP - Montpellier", root_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" <%= link_to "Home", root_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"<%= link_to "Créer un event", new_event_path %></a>
      </li>
    </ul>
    <ul class="my-2 my-lg-0">

      <% if current_user %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mon profil
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" <%= link_to "Mon profil", user_path(current_user.id) %></a>
          <a class="dropdown-item" href="#"></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item"   <%= link_to "Deconnexion", destroy_user_session_path, method: :delete %></a>
        </div>
      </li>
        <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            S'inscrire / Se connecter
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" <%= link_to "Se connecter", new_user_session_path %></a>
            <div class="dropdown-divider"></div>
          <a class="dropdown-item"   <%= link_to "S'inscrire", new_user_registration_path %></a>
        </li>
        <% end %>
    </ul>
  </div>
</nav>

<% if flash[:success] %>
<div class="alert alert-success" role="alert">
<div class="success text-center"><%= flash[:success]%></div>
</div>
<% elsif flash.now[:danger] %>
<div class="alert alert-danger" role="alert">
<div class="danger text-center"><%= flash.now[:danger]%></div>
</div>
<% elsif flash[:error] %>
<div class="alert alert-danger" role="alert">
<div class="danger text-center"><%= flash[:error]%></div>
</div>
<% else %>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>Ceci est le charges.html dans le layout</head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<style>
body
{background-image: url('http://4everstatic.com/images/abstrait/fond-de-couleur-220805.jpg');
   background-repeat: no-repeat;
   background-size:cover;
   background-attachment:fixed;}
</style>

<body>
<center>
  <% if flash[:success] %>
 <div class="alert alert-success" role="alert">
 <div class="success"><%= flash[:success]%></div>
 </div>
<% end %>
<br><br>
<div class="card card p-3 shadow" style="width: 18rem;">
  <img class="card-img-top" src="https://img.huffingtonpost.com/asset/5da6cd98210000140f34a123.jpeg?cache=kQdUrib9K7&ops=scalefit_630_noupscale" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= current_user.first_name %> <%= current_user.last_name %></h5>
    <p class="card-title"><strong>Bio : </strong><%= current_user.description %></p>
    <p class="card-title"><strong>Mail : </strong> <%= current_user.email %></p>
    <p class="card-title"><strong>Profile created on : </strong><%= current_user.created_at.strftime("%d/%m/%Y") %></p>
    <p class="card-text"> <strong>Last update on : </strong><%= current_user.updated_at.strftime("%d/%m/%Y") %></p>



<%= link_to 'Edit', edit_user_registration_path %> |
<%= link_to 'Back', users_path %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>